#!/bin/bash
#=====function-declare=====#

At[0]=108
At[1]=108
At[2]=108
At[3]=108
At[4]=108
At[5]=108
#=====read=====#

cnt=0;j=0;i=1;Ju=1
while read a b c
do
    if [[ $a != [0-5] ]];then	
	cnt=$(($cnt + 1))
	tmp[$cnt]=$a
	Ju=1
	if [[ $cnt != 1 ]];then	    
	    for k in $(seq 1 $((cnt-1)))
	    do
		if [[ ${tmp[$k]} == $a ]];then
		    Ju=$((Ju*0))
		else
		    Ju=$((Ju*1))
		fi
	    done
	fi
	if [[ $Ju = 1 ]] ;then
	    Sub[$i]=$a
	    i=$((i+1))
	fi
#debug:	echo ${tmp[@]} \| $a $Ju
#debug:	declare -p Sub
	let S_$a[$j-1]=$((S_$a[$j-1]+c-b))
	let Tols[$j-1]=$((Tols[$j-1]+c-b))
	let C_$a[$j-1]=$((C_$a[$j-1]+1))
#-------unit-transformation-----#
#	declare ah_$a[$cnt]=$((6+b/6)):$((b%6))0
#	declare ed_$a[$cnt]=$((6+c/6)):$((c%6))0
#	declare in_$a[$cnt]=$(((c-b)/6)):$(((c-b)%6))0
#	declare sm_$a[$j-1]=$((S_$a[$j-1]/6)):$((S_$a[$j-1]%6))0
#	declare sm_Tol[$j-1]=$((Tols[$j-1]/6)):$((Tols[$j-1]%6))0
#-------output-----#
	echo $a: $((6+b/6)):$((b%6))0-$((6+c/6)):$((c%6))0  \> $(((c-b)/6)):$(((c-b)%6))0
    else
	if [[ $j != 0 ]];then
	    for k in $(seq 1 $((i-1)))
	    do
		echo \ \ ${Sub[$k]}: $((S_${Sub[$k]}[$j-1]/6)):$((S_${Sub[$k]}[$j-1]%6))0
	    done
	fi
	echo =========
	echo \ \ Day:$a
	Cntic[$j]=$(($cnt+1))
	j=$(($j + 1))
    fi	  		
done < $1
Cntic[$j]=$(($cnt+1))
for k in $(seq 1 $((i-1)))
do
    echo \ \ ${Sub[$k]}: $((S_${Sub[$k]}[$j-1]/6)):$((S_${Sub[$k]}[$j-1]%6))0
done


#------comment-------#
echo \ 
echo ======================
for k in ${Tols[@]};do TolS=$((TolS+k));done
for k in $(seq 0 $((j-1)))
do
    AT=$((AT+At[$k]))
done
echo mean: $((TolS*100/AT))% \ Total ALL: $((TolS/6)):$((TolS%6))0/$((AT/6)):$((AT%6))0
for k in $(seq 0 $((j-1)))
do
    echo $k: $((Tols[$k]*100/At[$k]))% \  Total: $((Tols[$k]/6)):$((Tols[$k]%6))0/$((At[$k]/6)):$((At[$k]%6))0
done
echo ----------------------
for k in ${Sub[@]}
do
    echo $k:
    for l in $(seq 0 $((j-1)))
    do
	let As_$k=$((As_$k+S_$k[$l]))
	let Ac_$k=$((Ac_$k+C_$k[$l]))
    done
    echo Total: $((As_$k/6)):$((As_$k%6))0
    echo \ \ Occupy: $((As_$k*100/AT)).$(((As_$k*1000/AT)%10))% \ \ Aver-duration:  $(((As_$k/Ac_$k)/6)):$(((As_$k/Ac_$k)%6))0

done

