#!/bin/bash

log=$HOME/.logitime/log
list=$HOME/.logitime/list
tmp_=$HOME/.logitime/.tmp_
tmp=$HOME/.logitime/.tmp

#==================

if [ "$1" = "" ];then
    j=0;k=0
    echo -ne "\e[37m"
    echo -n "$(date +%w)": >> $log
    while [[ $j != 2 ]] && read -p "Head: " a d
    do
	i=0
	if [[ $a == [0-9] || $a == [0-9][0-9] ]];then
	    echo $a >> $log
   	    j=$((j+1))
	    if [[ $j == 2 ]];then
		sed -i '$d' $log
	    fi
	elif [ "$a" == 'exit' ];then
	    sed -i '$d' $log	    
	    j=2
	elif [ "$a" == 'delete' ];then
	    sed -i '$d' $log
	    sed -i '$d' $log
	    echo -n "$(date +%w)": >> $log	    
	    echo -e \ "\e[35malready deleted last event.\e[37m"
	elif [[ "$d" == "" ]];then
	    echo -n $a\ >> $log
	    while [[ "$i" != 2 ]] && read -p "Mark: " b c
	    do
		if [ "$b" == 'ti' ];then
		    H=$((10#$(date "+%H")))
		    M=$((10#$(date "+%M")))
		    if [[ $H == [0-3] ]];then
			H=$((24+H))
		    fi
		    ti=$((6*(H-6)+M/10+M%10/5))
		    echo -n $ti\ >> $log
		    echo -e \ "\e[36mmarked: $H:$(($M/10+M%10/5))0\e[37m"		
		    i=$((i+1))		
		elif [[ ($b == [0-9] || $b == [0-2][0-9])&&($c == [0-9] || $c == [0-5][0-9] ) ]];then
		    if [[ "$b" == [0-3] ]];then
			H=$((24+b))
		    else
			H=$b
		    fi
		    M=$c
		    ti=$((6*(H-6)+M/10+M%10/5))
		    echo -n $ti\ >> $log
		    echo -e \ "\e[36mmarked: $H:$(($M/10+M%10/5))0\e[37m"
		    i=$((i+1))
		elif [ "$b" == 'exit' ];then
		    sed -i '$d' $log
		    echo -n "$(date +%w)": >> $log		    
		    i=2
		    k=1
		else
		    echo -e \ "\e[31mError! retry please.\e[37m"
		fi
	    done
	    if [[ "$k" == 0 ]];then
		read -p "Note: " e
		echo $e >> $log
		if [ "$(grep "$a " $list)" = "" ];then
		    printf "$a 0000000000 U 0 $(date '+%F') $e\n" >> $list
		    echo -e "\033[35m Build.\033[37m"
		fi				
		read -p "Act:" f g
		if [ "$f" = 'done'  ];then
		    sed  "s#$a 0000000000 .#$a 0000000000 _#g" $list > $tmp_
		    if [[ $(diff $tmp_ $list) ]] ;then
			printf " \033[35m$a have marked as finished.\033[37m\n"
			mv $tmp_ $list
		    else
			printf " \033[35mNo such TO-DO.\033[37m\n"
		    fi
		    echo -n "$(date +%w)": >>$log
		elif [[ "$(echo $f|grep -P '(U|Z|E)')" != "" ]];then
		    sed  "s#$a 0000000000 .#$a 0000000000 $f#g" $list > $tmp_
		    if [[ $(diff $tmp_ $list) ]] ;then
			printf " \033[35m$a have marked changed.\033[37m\n"
			mv $tmp_ $list
		    else
			printf " \033[35mNo such TO-DO.\033[37m\n"
		    fi
		    echo -n "$(date +%w)": >>$log
		else
		    if [ "$(grep "$f " $list)" = "" ];then
			printf "$f 0000000000 U 0 $(date '+%F') $e\n" >> $list
			echo -e "\033[35m Build.\033[37m"
		    else
			echo -e "\033[35m Already existed.\033[37m"
		    fi
		    echo -n "$(date +%w)": >>$log
		fi
	    else
		echo -e "\033[35m Ignored.\033[37m"
	    fi	    
	else
	    k=0	    
	    echo -e \ "\e[31mIt's not a good Head.\e[37m"
	fi
    done
    echo -e \ "\e[35mexit!"
else
    printf "usage: ltlog [-r]\n"
fi
