#!/bin/bash

j=0;k=0
echo -ne "\e[37m"
while [[ $j != 2 ]] && read -p "Head: " a d
do
    i=0
    if [[ $a == [0-9] || $a == [0-9][0-9] ]];then
	echo $a >> $1
   	j=$((j+1))
	if [[ $j == 2 ]];then
	    sed -i '$d' $1
	fi
    elif [ $a == 'exit' ];then
	j=2
    elif [[ $d == "" ]];then
	echo -n $a\ >> $1
	while [[ $i != 2 ]] && read -p "Mark: " b c
	do
	    if [ $b == 'ti' ];then
		H=$((10#$(date "+%H")))
		M=$((10#$(date "+%M")))
		if [[ $H == [0-3] ]];then
		    H=$((24+H))
		fi
		ti=$((6*(H-6)+M/10+M%10/5))
		echo -n $ti\ >> $1
		echo -e \ "\e[36mmarked: $H:$(($M/10+M%10/5))0\e[37m"		
		i=$((i+1))		
	    elif [ $b == 'exit' ];then
		sed -i '$d' $1
		i=2
		k=1
	    elif [[ ($b == [0-9] || $b == [0-2][0-9])&&($c == [0-9] || $c == [0-5][0-9] ) ]];then
		if [[ $b == [0-3] ]];then
		    H=$((24+b))
		else
		    H=$b
		fi
		M=$c
		ti=$((6*(H-6)+M/10+M%10/5))
		echo -n $ti\ >> $1
		echo -e \ "\e[36mmarked: $H:$(($M/10+M%10/5))0\e[37m"
		i=$((i+1))		
	    else
		echo -e \ "\e[31mError! retry please.\e[37m"
	    fi
	done
	if [[ $k == 0 ]];then
	    echo \ >> $1
	else
	    k=0
	fi
	echo -e \ "\e[35mnext\e[37m"
    else
	echo -e \ "\e[31mIt's not a good Head.\e[37m"
    fi
done
echo -e \ "\e[35mexit!"

