#!/bin/bash


if [ "$(echo $1|grep -o -)" = '-' ];then
    if [ "$(echo $1|grep -o u)" = 'u' ];then
	while read a b c d e f
	do
	    [  "$(grep -c "$a" "$2")" != '1' ] && b_=_ || b_=$c
	    if [[ "$(echo $c|grep -o U)" != 'U' || "$e" = "$(date '+%F')" ]];then
		printf "$a 0000000000 $b_ $d $e $f\n" >> .tmp_
	    fi
	done <$2
	while read a b c d e f
	do	    
	    if [[ "$(echo $c|grep -o U)" = 'U' && "$e" != "$(date  '+%F')" ]];then
		d_=$((($(date -d "$(date +%F)" +%s)-$(date -d "$e" +%s))/86400))
		printf "$a 0000000000 $c $d_ $(date '+%F') $f\n" >> .tmp_
	    fi
	done <$2	
	mv .tmp_ $2
	echo " done."	
    fi
    if [  "$(echo $1|grep -o l)" = 'l' ];then
	if [ "$3" != "" ];then
	    grep -P "$3" "$2" > .tmp_
	    sort -ofuk1 .tmp_
	else
	    sort -fuk1 $2 > .tmp_
	fi
	while read a b c d e f
	do	
	    if [ "$(echo $1|grep -o 0)" = '0' ];then
		[[ "$d" = 0 || "$(echo $c|grep -o U)" = ""  ]] && d_=$d || d_="\033[33m$d\033[37m"
		printf "[$e]-$d_  \t"
	    fi
    	    _i=$a
	    while [[ "$(echo $_i|grep -Po "(?<=_).+")" != "" ]]
	    do
		_i=$(echo $_i|grep -Po "(?<=_).+")
		if [[ "$(echo $_i|grep -Po "(?<=_).+")" = "" ]];then
		    printf "├── "
		else
		    printf "    "
		fi
	    done
	    [[ "$(echo $c|grep -o U)" != "" &&  "$(grep -c "$a" "$2")" = '1' ]] && printf "\033[32m"   
	    if [ "$(echo $1|grep -o 1)" = '1' ];then
		printf "$_i\n"
	    else
		printf "$a\n"		    
	    fi
	    printf "\033[37m"
	done < .tmp_
	rm .tmp_
    elif [  "$(echo $1|grep -o a)" = 'a' ];then
	while read a b c d e
	do    
	    printf "$a[$c]=$d\t $e\n"
	done < $2
    elif [ "$(echo $1|grep -o x)" = 'x'  ];then
	read -p "evets input: " a b
	if [[  $b != ""  ]];then
	    printf "$a 0000000000 U 0 $(date '+%F') $b\n" >> $2
	else
	    echo " Invalid! try again."
	fi
    elif [ "$(echo $1|grep -o f)" = 'f' ];then
	    sed -i "s#$3 0000000000 U#$3 0000000000 _#g" $2 
    fi
else
    echo ==$(date)----
    echo ""
    grep U $1|grep -P "$(date '+%F')" > .tmp_
    while read a b c d e f g
    do
	if [[ "$(grep -c "$a" "$1")" = '1' && "$(echo $c|grep -o U)" != "" ]];then	    
	    if [ "$2" = "" ];then
		printf "\033[33m$d\033[37m-[\033[32m$a\033[37m] $f\n"
	    elif [ "$2" = "more"  ];then
		printf "\033[33m$d\033[37m-[\033[32m$a\033[37m] $f\n\t$g\n"
	    fi
	fi
    done < .tmp_
    rm .tmp_
    echo ""
fi
